### PR TITLE
add control point commands, read properties and rizer example

### PR DESCRIPTION
**Pull request by bytosaur**
#36 

- complete ftms write properties according to current BT standard
- add ftms target setting features (may be a braking change)
- modify ftms example to demonstrate the updates
- add tested rizer service and example

:)

### CODE REVIEW

**Comment by bytosaur** [comment]
@tensorturtle any idea why the linter is having a problem?

**Comment by zacharyedwardbull** [comment]
@bytosaur there is some cruft in the logs, I think I need to update the lint file. These are the lint errors relevant to your PR.

```
************* Module pycycling.fitness_machine_service
pycycling/fitness_machine_service.py:328:0: C0303: Trailing whitespace (trailing-whitespace)
pycycling/fitness_machine_service.py:374:0: C0303: Trailing whitespace (trailing-whitespace)
pycycling/fitness_machine_service.py:393:0: C0304: Final newline missing (missing-final-newline)
************* Module pycycling.rizer
pycycling/rizer.py:3:0: W1405: Quote delimiter ' is inconsistent with the rest of the file (inconsistent-quotes)
pycycling/rizer.py:4:0: W1405: Quote delimiter ' is inconsistent with the rest of the file (inconsistent-quotes)
pycycling/rizer.py:22:0: W1405: Quote delimiter ' is inconsistent with the rest of the file (inconsistent-quotes)
************* Module pycycling.ftms_parsers.fitness_machine_feature
pycycling/ftms_parsers/fitness_machine_feature.py:133:0: C0304: Final newline missing (missing-final-newline)
```

**Comment by zacharyedwardbull** [comment]
Hi @bytosaur, would you be able to address the lint errors then we can get this change merged in?
Cheers,
Zach

**Comment by bytosaur** [comment]
sorry it took me some time to get back to it! Thanks for describing the problem for me. I didn't use any formatter and I am not used to this kind of issue :D
Hope this is solved now :)

**Comment by bytosaur** [comment]
i think the fails for 3.9 and 3.10 is in the linter file as some terms are not recognized

**Comment by tensorturtle** [comment]
The linter errors in 3.9 and 3.10 have to do with some recent compatibility changes I made, I will take a look.

**Comment by tensorturtle** [comment]
The pylint complains about this line: https://github.com/zacharyedwardbull/pycycling/blob/a5998eb191edb1b2f2591d26b06f442a4f1ccff3/pycycling/sterzo.py#L31

This line preserves backwards compatibility for python versions less than 3.9.

I feel that we are justified in commenting ` # pylint: disable=deprecated-method ` on that line in order to skip the lint check, because we explicilty check for python version at runtime using `sys.version_info`.

The alternative would be to bump the minimum python version to 3.9, which I don't think is necessary. 

@bytosaur Could you add that pylint comment and attempt merge?

**Pull request merged**
